apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "microdatacenter.fullname" . }}-config
  labels:
    {{- include "microdatacenter.labels" . | nindent 4 }}
data:
  {{- range $key, $value := .Values.configMaps.appConfig }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}

{{- range $configMapName, $configMapData := .Values.configMaps.additional }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "microdatacenter.fullname" $ }}-{{ $configMapName }}
  labels:
    {{- include "microdatacenter.labels" $ | nindent 4 }}
data:
  {{- range $key, $value := $configMapData }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
{{- end }}